// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RustPlusBot.Persistence;

#nullable disable

namespace RustPlusBot.Persistence.Migrations
{
    [DbContext(typeof(BotDbContext))]
    [Migration("20260910150057_ChatWebhooks")]
    partial class ChatWebhooks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Persistord.Managed.Entities.ManagedWebhook", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChannelDiscordId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DiscordId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Scope", "Key")
                        .IsUnique();

                    b.ToTable("ManagedWebhooks", (string)null);
                });

            modelBuilder.Entity("RustPlusBot.Domain.Alarms.SmartAlarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LastIsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastTriggeredUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("PairedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PingEveryone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reachability")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("RelayToTeamChat")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("GuildId", "ServerId", "EntityId")
                        .IsUnique();

                    b.ToTable("SmartAlarms");
                });

            modelBuilder.Entity("RustPlusBot.Domain.Clans.ClanPlayerName", b =>
                {
                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("SteamId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ServerId", "SteamId");

                    b.HasIndex("GuildId");

                    b.ToTable("ClanPlayerNames");
                });

            modelBuilder.Entity("RustPlusBot.Domain.Clans.ClanState", b =>
                {
                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ClanId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TEXT");

                    b.Property<long>("Creator")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InvitesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxMemberCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MembersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Motd")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long?>("MotdAuthor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("MotdTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("RolesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("ServerId");

                    b.HasIndex("GuildId");

                    b.ToTable("ClanStates");
                });

            modelBuilder.Entity("RustPlusBot.Domain.Commands.ServerCommandSettings", b =>
                {
                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Muted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("ServerId");

                    b.HasIndex("GuildId");

                    b.ToTable("ServerCommandSettings");
                });

            modelBuilder.Entity("RustPlusBot.Domain.Connections.ConnectionState", b =>
                {
                    b.Property<Guid>("RustServerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveCredentialId")
                        .HasColumnType("TEXT");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PlayerCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("RustServerId");

                    b.HasIndex("GuildId");

                    b.ToTable("ConnectionStates");
                });

            modelBuilder.Entity("RustPlusBot.Domain.Credentials.FcmRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProtectedFcmCredentials")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "OwnerUserId")
                        .IsUnique();

                    b.ToTable("FcmRegistrations");
                });

            modelBuilder.Entity("RustPlusBot.Domain.Credentials.PlayerCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProtectedPlayerToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RustServerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SteamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RustServerId");

                    b.HasIndex("GuildId", "RustServerId", "OwnerUserId")
                        .IsUnique();

                    b.ToTable("PlayerCredentials");
                });

            modelBuilder.Entity("RustPlusBot.Domain.Guilds.GuildSettings", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PingEveryoneOnWipe")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuildId");

                    b.ToTable("GuildSettings");
                });

            modelBuilder.Entity("RustPlusBot.Domain.Map.ServerMapSettings", b =>
                {
                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GridStyle")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowGrid")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowMarkers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowMonuments")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowRigs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowTunnels")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowVendor")
                        .HasColumnType("INTEGER");

                    b.HasKey("ServerId");

                    b.HasIndex("GuildId");

                    b.ToTable("ServerMapSettings");
                });

            modelBuilder.Entity("RustPlusBot.Domain.Servers.RustServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AddedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("FacepunchServerId")
                        .HasColumnType("TEXT");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastMapSeed")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastMapSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastWipeTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FacepunchServerId");

                    b.HasIndex("GuildId");

                    b.HasIndex("GuildId", "Ip", "Port")
                        .IsUnique();

                    b.ToTable("RustServers");
                });

            modelBuilder.Entity("RustPlusBot.Domain.StorageMonitors.SmartStorageMonitor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("PairedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reachability")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("GuildId", "ServerId", "EntityId")
                        .IsUnique();

                    b.ToTable("SmartStorageMonitors");
                });

            modelBuilder.Entity("RustPlusBot.Domain.Switches.SmartSwitch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LastIsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("PairedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reachability")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("GuildId", "ServerId", "EntityId")
                        .IsUnique();

                    b.ToTable("SmartSwitches");
                });

            modelBuilder.Entity("RustPlusBot.Domain.Vending.VendingGridTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grid")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RegisteredBySteamId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("GuildId", "ServerId", "Grid")
                        .IsUnique();

                    b.ToTable("VendingGridTracks");
                });

            modelBuilder.Entity("RustPlusBot.Domain.Vending.VendingListingTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CostPerOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CurrencyIsBlueprint")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ItemIsBlueprint")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RegisteredByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("GuildId", "ServerId", "ItemId", "ItemIsBlueprint", "CurrencyId", "CurrencyIsBlueprint")
                        .IsUnique();

                    b.ToTable("VendingListingTracks");
                });

            modelBuilder.Entity("RustPlusBot.Domain.Vending.VendingNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CurrencyIsBlueprint")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ItemIsBlueprint")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PostedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReferenceCostPerOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReferenceQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("GuildId", "ServerId", "ItemId", "ItemIsBlueprint", "CurrencyId", "CurrencyIsBlueprint")
                        .IsUnique();

                    b.ToTable("VendingNotifications");
                });

            modelBuilder.Entity("RustPlusBot.Domain.Vending.VendingStockNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MachineId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PostedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoldOutSignature")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.HasIndex("GuildId", "ServerId", "MachineId")
                        .IsUnique();

                    b.ToTable("VendingStockNotifications");
                });

            modelBuilder.Entity("RustPlusBot.Domain.Workspace.ProvisionedCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DiscordCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RustServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RustServerId");

                    b.HasIndex("GuildId", "RustServerId")
                        .IsUnique();

                    b.ToTable("ProvisionedCategories");
                });

            modelBuilder.Entity("RustPlusBot.Domain.Workspace.ProvisionedChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DiscordChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RustServerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RustServerId");

                    b.HasIndex("GuildId", "RustServerId", "ChannelKey")
                        .IsUnique();

                    b.ToTable("ProvisionedChannels");
                });

            modelBuilder.Entity("RustPlusBot.Domain.Workspace.ProvisionedMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("DiscordChannelId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DiscordMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RustServerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RustServerId");

                    b.HasIndex("GuildId", "RustServerId", "MessageKey")
                        .IsUnique();

                    b.ToTable("ProvisionedMessages");
                });

            modelBuilder.Entity("RustPlusBot.Domain.Alarms.SmartAlarm", b =>
                {
                    b.HasOne("RustPlusBot.Domain.Servers.RustServer", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RustPlusBot.Domain.Clans.ClanPlayerName", b =>
                {
                    b.HasOne("RustPlusBot.Domain.Servers.RustServer", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RustPlusBot.Domain.Clans.ClanState", b =>
                {
                    b.HasOne("RustPlusBot.Domain.Servers.RustServer", null)
                        .WithOne()
                        .HasForeignKey("RustPlusBot.Domain.Clans.ClanState", "ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RustPlusBot.Domain.Commands.ServerCommandSettings", b =>
                {
                    b.HasOne("RustPlusBot.Domain.Servers.RustServer", null)
                        .WithOne()
                        .HasForeignKey("RustPlusBot.Domain.Commands.ServerCommandSettings", "ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RustPlusBot.Domain.Connections.ConnectionState", b =>
                {
                    b.HasOne("RustPlusBot.Domain.Servers.RustServer", null)
                        .WithOne()
                        .HasForeignKey("RustPlusBot.Domain.Connections.ConnectionState", "RustServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RustPlusBot.Domain.Credentials.PlayerCredential", b =>
                {
                    b.HasOne("RustPlusBot.Domain.Servers.RustServer", null)
                        .WithMany()
                        .HasForeignKey("RustServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RustPlusBot.Domain.Map.ServerMapSettings", b =>
                {
                    b.HasOne("RustPlusBot.Domain.Servers.RustServer", null)
                        .WithOne()
                        .HasForeignKey("RustPlusBot.Domain.Map.ServerMapSettings", "ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RustPlusBot.Domain.StorageMonitors.SmartStorageMonitor", b =>
                {
                    b.HasOne("RustPlusBot.Domain.Servers.RustServer", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RustPlusBot.Domain.Switches.SmartSwitch", b =>
                {
                    b.HasOne("RustPlusBot.Domain.Servers.RustServer", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RustPlusBot.Domain.Vending.VendingGridTrack", b =>
                {
                    b.HasOne("RustPlusBot.Domain.Servers.RustServer", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RustPlusBot.Domain.Vending.VendingListingTrack", b =>
                {
                    b.HasOne("RustPlusBot.Domain.Servers.RustServer", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RustPlusBot.Domain.Vending.VendingNotification", b =>
                {
                    b.HasOne("RustPlusBot.Domain.Servers.RustServer", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RustPlusBot.Domain.Vending.VendingStockNotification", b =>
                {
                    b.HasOne("RustPlusBot.Domain.Servers.RustServer", null)
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RustPlusBot.Domain.Workspace.ProvisionedCategory", b =>
                {
                    b.HasOne("RustPlusBot.Domain.Servers.RustServer", null)
                        .WithMany()
                        .HasForeignKey("RustServerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RustPlusBot.Domain.Workspace.ProvisionedChannel", b =>
                {
                    b.HasOne("RustPlusBot.Domain.Servers.RustServer", null)
                        .WithMany()
                        .HasForeignKey("RustServerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RustPlusBot.Domain.Workspace.ProvisionedMessage", b =>
                {
                    b.HasOne("RustPlusBot.Domain.Servers.RustServer", null)
                        .WithMany()
                        .HasForeignKey("RustServerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
