namespace RustPlusBot.Features.Commands.Localization;

/// <summary>The in-memory string catalog for command replies: culture -> (key -> value). English is the fallback.</summary>
internal sealed class CommandLocalizationCatalog
{
    /// <summary>culture -> key -> value.</summary>
    public required IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Strings { get; init; }

    /// <summary>The built-in EN/FR catalog.</summary>
    public static CommandLocalizationCatalog Default { get; } = new()
    {
        Strings = new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.Ordinal)
        {
            ["en"] = new Dictionary<string, string>(StringComparer.Ordinal)
            {
                ["command.mute.done"] = "Bot muted.",
                ["command.unmute.done"] = "Bot unmuted.",
                ["command.uptime.ok"] = "Uptime: {0}",
                ["command.pop.ok"] = "Pop: {0}/{1} ({2} queued)",
                ["command.time.ok"] = "Time: {0} — {1}",
                ["command.time.day"] = "day",
                ["command.time.night"] = "night",
                ["command.wipe.ok"] = "Wiped {0} ago",
                ["command.notconnected"] = "Not connected to the server.",
                ["command.wipe.unknown"] = "Wipe time is unknown.",
                ["command.online.ok"] = "Online ({0}): {1}",
                ["command.online.none"] = "No one is online.",
                ["command.offline.ok"] = "Offline ({0}): {1}",
                ["command.offline.none"] = "Everyone is online.",
                ["command.team.ok"] = "Team ({0}): {1}",
                ["command.team.none"] = "No team members.",
                ["command.team.nomatch"] = "No teammate matches '{0}'.",
                ["command.steamid.ok"] = "{0}",
                ["command.alive.ok"] = "Alive: {0}",
                ["command.alive.dead"] = "{0} dead",
                ["command.alive.member"] = "{0} {1}",
                ["command.prox.ok"] = "Prox: {0}",
                ["command.prox.member"] = "{0} {1}m",
                ["command.prox.selfunknown"] = "Can't locate you.",
                ["command.prox.alone"] = "No teammates nearby.",
                ["command.cargo.ok"] = "Cargo Ship at {0} ({1} ago)",
                ["command.cargo.none"] = "No cargo ship on the map.",
                ["command.heli.ok"] = "Patrol Helicopter at {0} ({1} ago)",
                ["command.heli.none"] = "No patrol helicopter on the map.",
                ["command.chinook.ok"] = "Chinook at {0} ({1} ago)",
                ["command.chinook.none"] = "No chinook on the map.",
                ["command.events.ok"] = "Recent: {0}",
                ["command.events.none"] = "No recent events.",
                ["command.event.cargoentered"] = "cargo in {0}",
                ["command.event.cargoleft"] = "cargo left {0}",
                ["command.event.helientered"] = "heli in {0}",
                ["command.event.helileft"] = "heli left {0}",
                ["command.event.chinookspawned"] = "chinook in {0}",
                ["command.server.none"] = "No server is set up yet.",
                ["command.server.specify"] = "Multiple servers are set up — choose one with the server option.",
                ["command.server.unknown"] = "That server isn't set up.",
                ["help.title"] = "Commands",
                ["help.group.control"] = "Control",
                ["help.group.server"] = "Server",
                ["help.group.teamintel"] = "Team",
                ["help.group.bot"] = "Bot",
                ["help.group.slash"] = "Slash commands",
                ["help.prefixnote"] = "Prefixes are configured per server; showing the default.",
                ["help.mute"] = "Silence all bot output to the game.",
                ["help.unmute"] = "Resume bot output to the game.",
                ["help.pop"] = "Show the server population.",
                ["help.time"] = "Show the in-game time.",
                ["help.wipe"] = "Show how long ago the server wiped.",
                ["help.online"] = "List online teammates.",
                ["help.offline"] = "List offline teammates.",
                ["help.team"] = "List all team members.",
                ["help.steamid"] = "Show teammates' Steam IDs.",
                ["help.alive"] = "Show how long each teammate has survived.",
                ["help.prox"] = "Show distance to each teammate.",
                ["help.uptime"] = "Show how long the bot has been running.",
                ["help.slash.help"] = "Show this help message.",
                ["help.slash.uptime"] = "Show the bot's uptime.",
                ["help.slash.leader"] = "Transfer in-game team leadership.",
                ["uptime.ok"] = "Bot uptime: {0}",
                ["leader.noserver"] = "No server is set up yet.",
                ["leader.notconnected"] = "Not connected to this server.",
                ["leader.noteam"] = "No team members to promote.",
                ["leader.pickserver"] = "Choose a server:",
                ["leader.pickmember"] = "Choose who to promote to team leader:",
                ["leader.success"] = "Promoted {0} to team leader.",
                ["leader.failure"] = "Couldn't promote — the server may be unreachable.",
            },
            ["fr"] = new Dictionary<string, string>(StringComparer.Ordinal)
            {
                ["command.mute.done"] = "Bot mis en sourdine.",
                ["command.unmute.done"] = "Bot réactivé.",
                ["command.uptime.ok"] = "Disponibilité : {0}",
                ["command.pop.ok"] = "Population : {0}/{1} ({2} en file)",
                ["command.time.ok"] = "Heure : {0} — {1}",
                ["command.time.day"] = "jour",
                ["command.time.night"] = "nuit",
                ["command.wipe.ok"] = "Wipe il y a {0}",
                ["command.notconnected"] = "Non connecté au serveur.",
                ["command.wipe.unknown"] = "Heure de wipe inconnue.",
                ["command.online.ok"] = "En ligne ({0}) : {1}",
                ["command.online.none"] = "Personne n'est en ligne.",
                ["command.offline.ok"] = "Hors ligne ({0}) : {1}",
                ["command.offline.none"] = "Tout le monde est en ligne.",
                ["command.team.ok"] = "Équipe ({0}) : {1}",
                ["command.team.none"] = "Aucun membre d'équipe.",
                ["command.team.nomatch"] = "Aucun coéquipier ne correspond à « {0} ».",
                ["command.steamid.ok"] = "{0}",
                ["command.alive.ok"] = "En vie : {0}",
                ["command.alive.dead"] = "{0} mort",
                ["command.alive.member"] = "{0} {1}",
                ["command.prox.ok"] = "Prox : {0}",
                ["command.prox.member"] = "{0} {1}m",
                ["command.prox.selfunknown"] = "Impossible de vous localiser.",
                ["command.prox.alone"] = "Aucun coéquipier à proximité.",
                ["command.cargo.ok"] = "Cargo en {0} (il y a {1})",
                ["command.cargo.none"] = "Aucun cargo sur la carte.",
                ["command.heli.ok"] = "Hélicoptère en {0} (il y a {1})",
                ["command.heli.none"] = "Aucun hélicoptère sur la carte.",
                ["command.chinook.ok"] = "Chinook en {0} (il y a {1})",
                ["command.chinook.none"] = "Aucun chinook sur la carte.",
                ["command.events.ok"] = "Récent : {0}",
                ["command.events.none"] = "Aucun événement récent.",
                ["command.event.cargoentered"] = "cargo en {0}",
                ["command.event.cargoleft"] = "cargo parti de {0}",
                ["command.event.helientered"] = "heli en {0}",
                ["command.event.helileft"] = "heli parti de {0}",
                ["command.event.chinookspawned"] = "chinook en {0}",
                ["command.server.none"] = "Aucun serveur n'est encore configuré.",
                ["command.server.specify"] =
                    "Plusieurs serveurs sont configurés — choisissez-en un avec l'option serveur.",
                ["command.server.unknown"] = "Ce serveur n'est pas configuré.",
                ["help.title"] = "Commandes",
                ["help.group.control"] = "Contrôle",
                ["help.group.server"] = "Serveur",
                ["help.group.teamintel"] = "Équipe",
                ["help.group.bot"] = "Bot",
                ["help.group.slash"] = "Commandes slash",
                ["help.prefixnote"] = "Les préfixes sont configurés par serveur ; affichage du préfixe par défaut.",
                ["help.mute"] = "Couper toute sortie du bot vers le jeu.",
                ["help.unmute"] = "Réactiver la sortie du bot vers le jeu.",
                ["help.pop"] = "Afficher la population du serveur.",
                ["help.time"] = "Afficher l'heure en jeu.",
                ["help.wipe"] = "Afficher depuis combien de temps le serveur a été wipe.",
                ["help.online"] = "Lister les coéquipiers en ligne.",
                ["help.offline"] = "Lister les coéquipiers hors ligne.",
                ["help.team"] = "Lister tous les membres de l'équipe.",
                ["help.steamid"] = "Afficher les identifiants Steam des coéquipiers.",
                ["help.alive"] = "Afficher depuis combien de temps chaque coéquipier survit.",
                ["help.prox"] = "Afficher la distance à chaque coéquipier.",
                ["help.uptime"] = "Afficher depuis combien de temps le bot fonctionne.",
                ["help.slash.help"] = "Afficher ce message d'aide.",
                ["help.slash.uptime"] = "Afficher la disponibilité du bot.",
                ["help.slash.leader"] = "Transférer le rôle de chef d'équipe en jeu.",
                ["uptime.ok"] = "Disponibilité du bot : {0}",
                ["leader.noserver"] = "Aucun serveur n'est encore configuré.",
                ["leader.notconnected"] = "Non connecté à ce serveur.",
                ["leader.noteam"] = "Aucun membre d'équipe à promouvoir.",
                ["leader.pickserver"] = "Choisissez un serveur :",
                ["leader.pickmember"] = "Choisissez qui promouvoir chef d'équipe :",
                ["leader.success"] = "{0} promu chef d'équipe.",
                ["leader.failure"] = "Impossible de promouvoir — le serveur est peut-être injoignable.",
            },
        },
    };
}
